/* =====================================================================
   SI Papara — « Observe et réponds » (format : en-tête de assets/observe.js).
   Une série de questions posées sur l'animation de la fiche pendant qu'elle
   bouge : l'élève regarde le mécanisme et nomme ce qu'il voit, comme à
   l'écrit avant tout calcul. Le panneau de réglages est caché ; la série
   règle l'animation avant chaque question.
   ===================================================================== */
window.SIP = window.SIP || {};
(function (SIP) {
  SIP.OBSERVE_BAC = SIP.OBSERVE_BAC || {};

  /* ---------------------------------------------------------------- DS 04
     Cinématique : lire un mouvement (animation « Quelle trajectoire pour chaque point ? ») */
  const ROT = { "mouvement de la piece": "rot", "position du point c": 60 };
  const TR = { "mouvement de la piece": "tr", "position du point c": 60 };
  const TC = { "mouvement de la piece": "tc", "position du point c": 60 };
  const PG = { "mouvement de la piece": "pg", "position du point c": 60 };
  const MVT = ["Translation rectiligne", "Translation circulaire", "Rotation autour d'un axe fixe", "Mouvement plan général"];
  const SANS = ["traces", "vitesses"];
  SIP.OBSERVE_BAC["meca-cinematique"] = {
    titre: "Lire un mouvement",
    consigne: "Le mécanisme bouge sous tes yeux, sans ses traces. Regarde la pièce et ses trois points A, B et C, puis réponds.",
    questions: [
      // ---- rotation
      { regler: ROT, boutons: ["lancer", "reprendre"], cacher: SANS,
        q: "Quel est le <b>mouvement de la pièce</b> par rapport au bâti ?", choix: MVT, bonne: 2,
        expl: "La pièce tourne autour de l'axe fixe O : c'est une <b>rotation</b>. Tous ses points décrivent des cercles de centre O." },
      { regler: ROT, cacher: SANS,
        q: "Quelle est la <b>trajectoire du point B</b> ?",
        choix: ["Un segment de droite", "Un cercle de centre O", "Un cercle dont le centre est sur la pièce", "Une courbe quelconque"], bonne: 1,
        expl: "En rotation autour de O, chaque point décrit un <b>cercle de centre O</b>, de rayon sa distance à l'axe : pour B, R = OB = 120 mm." },
      { regler: ROT, cacher: SANS,
        q: "Lequel des trois points va le <b>plus vite</b> ?",
        choix: ["A", "B", "C", "Les trois vont à la même vitesse"], bonne: 1,
        expl: "v = R·ω : la vitesse angulaire ω est la même pour toute la pièce, donc le point le plus loin de l'axe va le plus vite. B est à 120 mm de O, C à 60 mm, A à 41 mm." },
      { regler: ROT, cacher: SANS,
        q: "À chaque instant, le <b>vecteur vitesse</b> de B est…",
        choix: ["Dirigé vers O", "Dirigé vers l'extérieur du cercle", "Tangent au cercle, perpendiculaire à OB", "Toujours horizontal"], bonne: 2,
        expl: "La vitesse est toujours <b>tangente à la trajectoire</b>. Sur un cercle de centre O, elle est perpendiculaire au rayon OB." },
      // ---- translation rectiligne
      { regler: TR, cacher: SANS,
        q: "Quel est le <b>mouvement de la pièce</b> par rapport au bâti ?", choix: MVT, bonne: 0,
        expl: "La pièce monte et descend entre deux glissières <b>sans tourner</b> : elle garde son orientation, ses points décrivent des segments parallèles. C'est une <b>translation rectiligne</b>." },
      { regler: TR, cacher: SANS,
        q: "Quelle est la <b>trajectoire du point A</b> ?",
        choix: ["Un segment de droite vertical", "Un cercle", "Un arc de cercle", "Une courbe quelconque"], bonne: 0,
        expl: "En translation rectiligne, tous les points décrivent des <b>segments parallèles de même longueur</b> : la course de la pièce." },
      { regler: TR, cacher: SANS,
        q: "À un instant donné, les <b>vecteurs vitesse</b> de A, B et C sont…",
        choix: ["Identiques : même direction, même sens, même norme", "De même direction mais de normes différentes", "De directions différentes", "Nuls, sauf celui de B"], bonne: 0,
        expl: "En translation, <b>tous les points ont le même vecteur vitesse</b> à chaque instant : la pièce se déplace « d'un bloc »." },
      // ---- translation circulaire
      { regler: TC, cacher: SANS,
        q: "Quel est le <b>mouvement de la pièce</b> par rapport au bâti ?", choix: MVT, bonne: 1,
        expl: "Piège classique : la pièce est portée par deux manivelles qui tournent, mais elle <b>reste toujours horizontale</b>. Ses points décrivent des cercles : c'est une <b>translation circulaire</b>, pas une rotation." },
      { regler: TC, cacher: SANS,
        q: "Quelle est la <b>trajectoire du point C</b> ?",
        choix: ["Un cercle de rayon égal à la longueur des manivelles", "Un cercle de centre O1", "Un segment de droite", "Une courbe quelconque"], bonne: 0,
        expl: "En translation circulaire, chaque point décrit un <b>cercle de même rayon que les manivelles</b> (45 mm), mais de centre différent : le centre de la trajectoire de C n'est ni O1 ni O2." },
      { regler: TC, cacher: SANS,
        q: "Pendant le mouvement, la <b>pièce</b> elle-même…",
        choix: ["Garde toujours la même orientation", "Tourne d'un tour par tour de manivelle", "Tourne d'un demi-tour", "Change d'orientation puis revient"], bonne: 0,
        expl: "Les deux manivelles sont égales et parallèles : la pièce <b>garde son orientation</b>. C'est ce qui distingue une translation (même circulaire) d'une rotation." },
      // ---- bielle-manivelle
      { regler: PG, cacher: SANS,
        q: "Quel est le <b>mouvement de la pièce</b> (la bielle) par rapport au bâti ?", choix: MVT, bonne: 3,
        expl: "La bielle <b>tourne et se déplace en même temps</b> : un bout suit la manivelle, l'autre le piston. Ni translation, ni rotation : <b>mouvement plan général</b>. Chaque point a sa propre trajectoire." },
      { regler: PG, cacher: SANS,
        q: "Quelle est la <b>trajectoire du point B</b>, lié au piston ?",
        choix: ["Un segment de droite", "Un cercle", "Une ellipse", "Une courbe quelconque"], bonne: 0,
        expl: "B est guidé par le piston dans sa glissière : il va et vient sur un <b>segment de droite</b> horizontal. Sa course vaut deux fois le rayon de la manivelle." },
      { regler: { "mouvement de la piece": "pg", "position du point c": 0 }, cacher: SANS,
        q: "C est placé sur l'axe de la manivelle (à 0 mm). Quelle est sa <b>trajectoire</b> ?",
        choix: ["Un cercle", "Un segment de droite", "Une ellipse", "Une courbe quelconque"], bonne: 0,
        expl: "Ce point est aussi un point de la manivelle, qui est en rotation : il décrit un <b>cercle</b> de rayon 40 mm. Les points de la bielle entre la manivelle et le piston décrivent des courbes fermées, entre le cercle et le segment." },
      { regler: PG, cacher: SANS,
        q: "La <b>vitesse du piston</b> (point B) est nulle quand…",
        choix: ["La manivelle et la bielle sont alignées (points morts)", "La manivelle est perpendiculaire à la bielle", "Jamais : le moteur tourne sans arrêt", "La bielle est horizontale"], bonne: 0,
        expl: "Aux <b>points morts</b>, le piston change de sens : sa vitesse passe par zéro, alors que la manivelle tourne à vitesse constante. C'est pour cela que la vitesse d'un piston n'est pas constante." },
    ],
  };

  /* ---------------------------------------------------------------- DS 04
     Transmetteurs : lire un réducteur (animation « Réducteur : vitesse contre couple »).
     Moteur fixé : Ne = 1 500 tr/min, Ce = 2,00 N·m. */
  const ENG = (Z1, Z2, eta = 0.9) => ({ "type de transmetteur": "eng", "dents de la roue menante": Z1, "dents de la roue menee": Z2, "rendement": eta });
  const PC = (Z1, Z2, eta = 0.9) => ({ "type de transmetteur": "pc", "dents de la roue menante": Z1, "dents de la roue menee": Z2, "rendement": eta });
  const VAL = ["valeurs"];
  SIP.OBSERVE_BAC["meca-transmission"] = {
    titre: "Lire un réducteur",
    consigne: "Les deux roues tournent sous tes yeux (ralenties 100 fois), avec leur repère coloré et leur compteur de tours. Regarde-les, puis réponds.",
    questions: [
      { regler: ENG(15, 45), cacher: VAL,
        q: "Pignon de 15 dents sur le moteur, roue de 45 dents en sortie. <b>Laquelle tourne le plus vite</b> ?",
        choix: ["La roue menante (15 dents)", "La roue menée (45 dents)", "Les deux à la même vitesse", "Ça dépend du rendement"], bonne: 0,
        expl: "Compte les tours affichés : la petite roue fait <b>3 tours</b> pendant que la grande en fait 1. N<sub>s</sub> = N<sub>e</sub>·Z<sub>1</sub>/Z<sub>2</sub> = 1 500 × 15/45 = 500 tr/min." },
      { regler: ENG(15, 45), cacher: VAL,
        q: "Dans quel <b>sens</b> tourne la roue de sortie par rapport à la roue d'entrée ?",
        choix: ["Dans le sens opposé", "Dans le même sens", "Elle ne tourne pas", "Tantôt l'un, tantôt l'autre"], bonne: 0,
        expl: "Deux roues dentées en contact <b>extérieur</b> tournent en sens inverse : au point de contact, les dents des deux roues avancent dans la même direction, donc les centres tournent en sens contraires." },
      { regler: PC(15, 45), cacher: VAL,
        q: "Avec la <b>courroie crantée</b>, la poulie de sortie tourne…",
        choix: ["Dans le même sens que la poulie d'entrée", "En sens inverse", "Plus vite que l'entrée", "À la même vitesse que l'entrée"], bonne: 0,
        expl: "Une courroie droite (non croisée) transmet le mouvement <b>sans inverser le sens</b>. Le rapport reste Z<sub>1</sub>/Z<sub>2</sub> = 1/3 : la sortie tourne 3 fois moins vite." },
      { regler: ENG(15, 45), cacher: VAL,
        q: "Quand la roue de sortie a fait <b>un tour</b> complet, la roue d'entrée en a fait…",
        choix: ["3", "1/3", "1", "45"], bonne: 0,
        expl: "Les deux roues laissent passer le même nombre de dents : 45 dents = <b>3 tours</b> de la roue de 15 dents. D'où r = N<sub>s</sub>/N<sub>e</sub> = Z<sub>1</sub>/Z<sub>2</sub> = 1/3." },
      { regler: ENG(15, 45), cacher: VAL,
        q: "Le <b>rapport de transmission</b> r = N<sub>s</sub>/N<sub>e</sub> vaut ici…",
        choix: ["1/3 ≈ 0,333", "3", "45", "0,9"], bonne: 0,
        expl: "r = Z<sub>1</sub>/Z<sub>2</sub> = 15/45 = <b>1/3</b> : c'est un réducteur (r &lt; 1). Le rendement n'intervient pas dans le rapport des vitesses, fixé par les dents." },
      { regler: ENG(40, 20), cacher: VAL,
        q: "Roue menante de 40 dents, roue menée de 20 dents. La sortie tourne…",
        choix: ["2 fois plus vite que l'entrée", "2 fois moins vite que l'entrée", "À la même vitesse", "20 fois plus vite"], bonne: 0,
        expl: "r = 40/20 = 2 : un <b>multiplicateur</b>. N<sub>s</sub> = 3 000 tr/min, mais le couple de sortie est divisé par 2, et encore réduit par le rendement." },
      { regler: ENG(15, 45, 1), cacher: VAL,
        q: "Regarde l'<b>épaisseur des flèches de couple</b>. Avec η = 1, le couple de sortie est…",
        choix: ["3 fois plus grand que le couple d'entrée", "3 fois plus petit", "Égal au couple d'entrée", "Nul"], bonne: 0,
        expl: "Sans pertes, P<sub>s</sub> = P<sub>e</sub>, donc C<sub>s</sub>·ω<sub>s</sub> = C<sub>e</sub>·ω<sub>e</sub> : la sortie tourne 3 fois moins vite, son couple est <b>3 fois plus grand</b> : 6,00 N·m." },
      { regler: ENG(15, 45, 0.5), cacher: VAL,
        q: "On passe le rendement de 1 à <b>0,5</b>. Qu'est-ce qui change ?",
        choix: ["La vitesse de sortie reste la même, le couple de sortie est divisé par 2", "La vitesse de sortie est divisée par 2", "La vitesse et le couple sont divisés par 2", "Rien : le rendement ne concerne que la chaleur"], bonne: 0,
        expl: "Le rapport des vitesses est fixé par les dents. Les pertes se paient <b>en couple</b> : C<sub>s</sub> = η·C<sub>e</sub>/r = 0,5 × 2 × 3 = 3,00 N·m, et P<sub>s</sub> = 0,5·P<sub>e</sub>." },
      { regler: ENG(15, 45, 0.9), cacher: VAL,
        q: "La <b>puissance de sortie</b>, comparée à la puissance du moteur (η = 0,9)…",
        choix: ["Vaut 90 % de la puissance d'entrée", "Est 3 fois plus grande", "Est 3 fois plus petite", "Est égale"], bonne: 0,
        expl: "Un réducteur ne crée pas de puissance : P<sub>s</sub> = η·P<sub>e</sub>. Les 10 % manquants <b>chauffent</b> les engrenages (frottement des dents, roulements)." },
      { regler: ENG(20, 20), cacher: VAL,
        q: "Même nombre de dents (20 et 20). À quoi sert cet engrenage ?",
        choix: ["À inverser le sens de rotation sans changer la vitesse", "À doubler la vitesse", "À doubler le couple", "À rien"], bonne: 0,
        expl: "r = 1 : même vitesse, couple de sortie η·C<sub>e</sub>. Seul le <b>sens</b> change, ce qu'une courroie ne ferait pas." },
      { regler: ENG(15, 45), cacher: VAL,
        q: "Un <b>réducteur</b> comme celui-ci sert à…",
        choix: ["Réduire la vitesse et augmenter le couple", "Augmenter la vitesse et le couple", "Réduire la vitesse et le couple", "Augmenter la puissance"], bonne: 0,
        expl: "Un moteur tourne vite avec peu de couple ; la roue du robot a besoin de couple à vitesse modérée : le réducteur <b>échange l'un contre l'autre</b>, aux pertes près." },
      { regler: PC(15, 45), cacher: VAL,
        q: "Poulies crantées de 15 et 45 dents. Le rapport de transmission…",
        choix: ["Vaut aussi 1/3 : il se calcule avec les nombres de dents des poulies", "Vaut 3", "Ne se calcule pas sans la longueur de la courroie", "Dépend de la tension de la courroie"], bonne: 0,
        expl: "Pour une courroie crantée comme pour un engrenage, r = Z<sub>1</sub>/Z<sub>2</sub> (ou D<sub>1</sub>/D<sub>2</sub> pour des poulies lisses). La courroie transmet le mouvement sans glisser." },
    ],
  };

  /* ---------------------------------------------------------------- DS 04
     2e loi de Newton : lire un mouvement (animation « Force, masse et accélération »).
     Chaque question relance l'essai : chariot sur 3 m, points toutes les 0,2 s, courbe v(t). */
  const CH = (F, m, f, v0) => ({ "force motrice": F, "masse du chariot": m, "frottement": f, "vitesse au depart": v0 });
  const LANCER = ["lancer"], VEC = ["vecteurs"];
  SIP.OBSERVE_BAC["phy-newton"] = {
    titre: "Lire un mouvement",
    consigne: "À chaque question, l'essai est lancé : regarde le chariot, les points relevés toutes les 0,2 s sous la piste et la courbe v(t), puis réponds.",
    questions: [
      { regler: CH(6, 2, 2, 0), boutons: LANCER, cacher: VEC,
        q: "F = 6 N, f = 2 N, m = 2 kg, départ arrêté. Les <b>points relevés</b> toutes les 0,2 s sont…",
        choix: ["De plus en plus espacés", "Régulièrement espacés", "De moins en moins espacés", "Tous au même endroit"], bonne: 0,
        expl: "ΣF = 6 − 2 = 4 N vers l'avant : le chariot <b>accélère</b> (a = 2 m/s²). En un même intervalle de 0,2 s, il parcourt de plus en plus de distance." },
      { regler: CH(6, 2, 2, 0), boutons: LANCER, cacher: VEC,
        q: "Même essai. La <b>courbe v(t)</b> tracée est…",
        choix: ["Une droite qui monte", "Une droite horizontale", "Une courbe qui s'arrondit", "Une droite qui descend"], bonne: 0,
        expl: "Accélération constante : v = a·t, une <b>droite de pente a</b>. Sa pente se lit sur le graphe : 2 m/s gagnés chaque seconde." },
      { regler: CH(6, 2, 2, 0), boutons: LANCER, cacher: VEC,
        q: "D'après la <b>pente</b> de la droite v(t), l'accélération vaut environ…",
        choix: ["2 m/s²", "4 m/s²", "6 m/s²", "0,5 m/s²"], bonne: 0,
        expl: "v passe de 0 à 2 m/s en 1 s : a = Δv/Δt = <b>2 m/s²</b>. Vérification par la 2<sup>e</sup> loi : a = ΣF/m = (6 − 2)/2 = 2 m/s²." },
      { regler: CH(6, 4, 2, 0), boutons: LANCER, cacher: VEC,
        q: "Masse <b>doublée</b> (4 kg), même force, même frottement. L'accélération…",
        choix: ["Est divisée par 2", "Est doublée", "Ne change pas", "Devient nulle"], bonne: 0,
        expl: "a = ΣF/m = 4/4 = <b>1 m/s²</b> : la droite v(t) est deux fois moins pentue et les points se resserrent." },
      { regler: CH(2, 2, 2, 2), boutons: LANCER, cacher: VEC,
        q: "F = f = 2 N et le chariot part à 2 m/s. Que fait-il ?",
        choix: ["Il avance à vitesse constante", "Il accélère", "Il ralentit puis s'arrête", "Il s'arrête tout de suite"], bonne: 0,
        expl: "ΣF = 0 : <b>principe d'inertie</b>, mouvement rectiligne uniforme. Points régulièrement espacés, v(t) horizontale à 2 m/s." },
      { regler: CH(0, 2, 2, 3), boutons: LANCER, cacher: VEC,
        q: "Plus de force motrice, seulement le frottement, départ à 3 m/s. Les points relevés sont…",
        choix: ["De moins en moins espacés : il ralentit", "De plus en plus espacés", "Régulièrement espacés", "Il n'y a pas de points : il ne bouge pas"], bonne: 0,
        expl: "ΣF = −2 N vers l'arrière : a = −1 m/s². v(t) est une droite qui <b>descend</b> ; il franchit quand même l'arrivée (3 m) avant de s'arrêter, à 4,5 m." },
      { regler: CH(2, 2, 2, 0), boutons: LANCER, cacher: VEC,
        q: "F = f = 2 N et le chariot est <b>à l'arrêt</b>. Que se passe-t-il ?",
        choix: ["Il ne démarre pas : ΣF = 0", "Il démarre lentement", "Il recule", "Il démarre puis s'arrête"], bonne: 0,
        expl: "Le frottement d'<b>adhérence</b> équilibre la force motrice tant qu'elle ne dépasse pas f : la somme des forces est nulle, le chariot reste immobile." },
      { regler: CH(6, 2, 2, 0), boutons: LANCER,
        q: "Regarde au-dessus du chariot : le vecteur ΣF (bleu) et le vecteur a (vert) sont…",
        choix: ["Colinéaires et de même sens", "Perpendiculaires", "De sens opposés", "Toujours vers l'avant, quel que soit le mouvement"], bonne: 0,
        expl: "ΣF = m·a : a a la <b>direction et le sens</b> de ΣF, et sa norme vaut ΣF/m. Ici 4 N et 2 m/s², vers l'avant. Quand le chariot freine, les deux pointent vers l'arrière." },
      { regler: CH(6, 2, 4, 0), boutons: LANCER, cacher: VEC,
        q: "Le frottement passe de 2 N à <b>4 N</b> (F = 6 N, m = 2 kg). L'accélération…",
        choix: ["Est divisée par 2 : a = 1 m/s²", "Ne change pas", "Devient nulle", "Est doublée"], bonne: 0,
        expl: "ΣF = 6 − 4 = 2 N, a = 2/2 = <b>1 m/s²</b>. Ce n'est pas F seule qui compte, mais la <b>somme</b> des forces." },
      { regler: CH(6, 2, 2, 0), boutons: LANCER, cacher: VEC,
        q: "F = 6 N, f = 2 N, m = 2 kg. D'après les points relevés, le chariot franchit les 3 m en environ…",
        choix: ["1,7 s", "3 s", "1 s", "0,5 s"], bonne: 0,
        expl: "Environ 9 points à 0,2 s d'intervalle, et la droite v(t) s'arrête vers t = 1,7 s. Calcul : x = ½·a·t², donc t = √(2 × 3/2) = <b>1,73 s</b>." },
    ],
  };

  /* ---------------------------------------------------------------- DS 02
     Statique : lire les appuis (animation « Où placer le lest ? », L = 12 cm). */
  const RB = (a, m = 0.8, f = 0.7) => ({ "position de g": a, "masse du robot": m, "coefficient d'adherence": f });
  SIP.OBSERVE_BAC["meca-statique"] = {
    titre: "Lire les appuis",
    consigne: "Le robot est posé sur ses roues : regarde les flèches des actions du sol et la position de G, puis réponds.",
    questions: [
      { regler: RB(4), cacher: VAL,
        q: "Regarde les deux flèches du sol. Quel appui <b>porte le plus</b> ?",
        choix: ["Les roues motrices (M)", "La roue folle (F)", "Les deux autant", "Aucun : le poids est porté par le lest"], bonne: 0,
        expl: "G est à 4 cm des roues motrices et à 8 cm de la roue folle : l'appui <b>le plus proche de G</b> porte le plus. N<sub>M</sub> = P·(L − a)/L = 2/3 de P." },
      { regler: RB(6), cacher: VAL,
        q: "G au milieu des deux appuis (a = 6 cm). Les flèches N<sub>M</sub> et N<sub>F</sub> sont…",
        choix: ["Égales : chaque appui porte la moitié du poids", "N<sub>M</sub> deux fois plus grande", "N<sub>F</sub> deux fois plus grande", "Nulles"], bonne: 0,
        expl: "Moments en M : N<sub>F</sub>·L = P·a avec a = L/2, donc N<sub>F</sub> = P/2, et N<sub>M</sub> = P − N<sub>F</sub> = P/2." },
      { regler: RB(10), cacher: VAL,
        q: "G à 10 cm des roues motrices, 2 cm de la roue folle. Qui porte le plus ?",
        choix: ["La roue folle : 5/6 du poids", "Les roues motrices", "Les deux autant", "Le robot bascule"], bonne: 0,
        expl: "N<sub>F</sub> = P·a/L = P × 10/12 : la roue folle porte <b>83 %</b> du poids ; il ne reste que 17 % sur les motrices, mauvais pour l'adhérence." },
      { regler: RB(0), cacher: VAL,
        q: "G exactement au-dessus de l'axe des roues motrices (a = 0). La roue folle porte…",
        choix: ["Rien : tout le poids est sur les roues motrices", "La moitié du poids", "Tout le poids", "Un tiers du poids"], bonne: 0,
        expl: "Moments en M : N<sub>F</sub>·L = P·a = 0. C'est la position <b>idéale</b> pour l'adhérence : la poussée maximale f·N<sub>M</sub> est la plus grande possible." },
      { regler: RB(-2), cacher: VAL,
        q: "G <b>derrière</b> l'axe des roues motrices (a = −2 cm). Que se passe-t-il ?",
        choix: ["Le robot bascule en arrière : la roue folle décolle", "La roue folle porte un peu plus", "Rien de particulier", "Le robot avance tout seul"], bonne: 0,
        expl: "Il faudrait N<sub>F</sub> &lt; 0, un sol qui <b>tire</b> : impossible, un appui ne peut que pousser. Le robot se cabre autour de l'axe des roues motrices." },
      { regler: RB(4, 1.2), cacher: VAL,
        q: "On passe la masse de 0,8 kg à <b>1,2 kg</b> sans bouger G. Les flèches…",
        choix: ["Grandissent dans les mêmes proportions : la répartition (en %) ne change pas", "Seule N<sub>M</sub> grandit", "Seule N<sub>F</sub> grandit", "Ne changent pas"], bonne: 0,
        expl: "N<sub>F</sub> = P·a/L et N<sub>M</sub> = P·(L − a)/L, toutes deux proportionnelles à P. La part sur les motrices reste 67 % : c'est la <b>position de G</b> qui fixe la répartition." },
      { regler: RB(4), cacher: VAL,
        q: "Pour pousser le plus fort possible sans patiner, il faut placer G…",
        choix: ["Le plus près possible de l'axe des roues motrices, sans passer derrière", "Au-dessus de la roue folle", "Au milieu des deux appuis", "Le plus haut possible"], bonne: 0,
        expl: "Poussée maximale = f·N<sub>M</sub>. N<sub>M</sub> est maximal pour a = 0 ; derrière, le robot bascule. Le lest se place donc <b>juste au-dessus de l'axe des motrices</b>." },
      { regler: RB(4, 0.8, 0.35), cacher: VAL,
        q: "Même robot, piste deux fois moins adhérente (f = 0,35). Les flèches N<sub>M</sub> et N<sub>F</sub>…",
        choix: ["Ne changent pas", "Sont divisées par 2", "Sont doublées", "Disparaissent"], bonne: 0,
        expl: "Les actions normales du sol ne dépendent que du poids et de la position de G. Seule la <b>poussée maximale</b> f·N<sub>M</sub> est divisée par 2." },
      { regler: RB(4), cacher: VAL,
        q: "La flèche du poids P part de G. Elle est…",
        choix: ["Verticale, vers le bas", "Verticale, vers le haut", "Horizontale", "Dirigée vers les roues motrices"], bonne: 0,
        expl: "Le poids s'applique au <b>centre de gravité</b>, verticalement vers le bas : P = m·g = 0,8 × 9,81 = 7,85 N." },
      { regler: RB(4), cacher: VAL,
        q: "Les trois flèches P, N<sub>M</sub> et N<sub>F</sub> vérifient…",
        choix: ["N<sub>M</sub> + N<sub>F</sub> = P : les actions du sol équilibrent le poids", "N<sub>M</sub> = N<sub>F</sub>", "N<sub>M</sub> − N<sub>F</sub> = P", "N<sub>M</sub> + N<sub>F</sub> = 2·P"], bonne: 0,
        expl: "Robot en équilibre (PFS) : somme des forces nulle sur la verticale, N<sub>M</sub> + N<sub>F</sub> − P = 0 ; somme des moments nulle en M, N<sub>F</sub>·L − P·a = 0." },
      { regler: RB(13), cacher: VAL,
        q: "G <b>au-delà</b> de la roue folle (a = 13 cm). Que se passe-t-il ?",
        choix: ["Le robot bascule en avant sur sa roue folle", "Les roues motrices portent tout", "Rien de particulier", "Il recule"], bonne: 0,
        expl: "N<sub>M</sub> = P·(L − a)/L deviendrait négatif : impossible. Le robot <b>pique du nez</b> autour de la roue folle." },
    ],
  };

  /* ---------------------------------------------------------------- DS 02
     Actions mécaniques : lire un bras de levier (animation « Le bras de levier »). */
  const LV = (th, F = 80, OA = 0.25, sens = 1) => ({ "inclinaison": th, "force f": F, "longueur du levier": OA, "sens de f": sens });
  const MOM = ["moment"];
  SIP.OBSERVE_BAC["meca-actions"] = {
    titre: "Lire un bras de levier",
    consigne: "Regarde la force F, sa droite d'action en pointillés et le bras de levier d en bleu, puis réponds.",
    questions: [
      { regler: LV(90),
        q: "La force est <b>perpendiculaire</b> au levier (θ = 90°). Le bras de levier d (en bleu) vaut…",
        choix: ["OA : toute la longueur du levier", "La moitié de OA", "Zéro", "La longueur de la flèche F"], bonne: 0,
        expl: "d = OA·sin θ = OA·sin 90° = OA = 0,25 m. C'est la plus grande valeur possible : le moment est <b>maximal</b>, M = F·OA = 20,0 N·m." },
      { regler: LV(0),
        q: "La force est dans l'<b>axe du levier</b> (θ = 0°). Le bras de levier…",
        choix: ["Est nul : la droite d'action de F passe par O", "Vaut OA", "Vaut la moitié de OA", "N'existe pas"], bonne: 0,
        expl: "La droite d'action de F passe par O : d = 0, le moment est <b>nul</b>. Tirer une porte dans l'axe de ses gonds ne la fait pas tourner." },
      { regler: LV(30),
        q: "θ = 30°. Compare d (en bleu) à OA.",
        choix: ["d est la moitié de OA", "d = OA", "d est plus grand que OA", "d est nul"], bonne: 0,
        expl: "d = OA·sin 30° = <b>OA/2</b> = 0,125 m. Le moment vaut F·d = 80 × 0,125 = 10,0 N·m, la moitié du moment à 90°." },
      { regler: LV(150),
        q: "θ = 150°. Le bras de levier, comparé à celui de 30°…",
        choix: ["Est le même : sin 150° = sin 30°", "Est cinq fois plus grand", "Est nul", "Est négatif"], bonne: 0,
        expl: "d = OA·sin 150° = OA/2 aussi. La force penche de l'autre côté, mais sa droite d'action passe <b>à la même distance</b> de O." },
      { regler: LV(90, 40),
        q: "On divise la force par 2 (θ = 90°). Le moment en O…",
        choix: ["Est divisé par 2", "Ne change pas", "Est doublé", "Devient nul"], bonne: 0,
        expl: "M = F·d avec d inchangé (OA) : M = 40 × 0,25 = <b>10,0 N·m</b> au lieu de 20,0 N·m. La flèche courbe du moment est plus fine." },
      { regler: LV(90, 80, 0.1),
        q: "Levier raccourci à 0,10 m (θ = 90°). Le moment…",
        choix: ["Est divisé par 2,5 : d passe de 0,25 à 0,10 m", "Ne change pas", "Est multiplié par 2,5", "Change de signe"], bonne: 0,
        expl: "M = F·OA = 80 × 0,10 = <b>8,00 N·m</b> au lieu de 20,0 N·m. Un levier plus long donne plus de moment pour la même force." },
      { regler: LV(60, 80, 0.25, -1), cacher: MOM,
        q: "La force tire <b>vers le bas</b>. Le levier tourne…",
        choix: ["Dans le sens horaire : le moment est négatif", "Dans le sens trigonométrique : le moment est positif", "Il ne tourne pas", "Dans les deux sens"], bonne: 0,
        expl: "F vers le bas, appliquée en A à droite de O, fait tourner le levier dans le sens <b>horaire</b> : M = −F·d. Le signe dit le sens, la valeur dit l'intensité." },
      { regler: LV(60, 80, 0.25, 1), cacher: MOM,
        q: "Même force, mais <b>vers le haut</b>. Le moment…",
        choix: ["A la même valeur et le signe opposé : sens trigonométrique", "Est nul", "Est doublé", "A le même signe"], bonne: 0,
        expl: "Même d, même F : |M| = 80 × 0,25 × sin 60° = 17,3 N·m, mais la rotation est dans l'autre sens : <b>M &gt; 0</b>." },
      { regler: LV(60),
        q: "Le point H (en bleu) est…",
        choix: ["Le pied de la perpendiculaire abaissée de O sur la droite d'action de F", "Le milieu de OA", "Le point d'application de F", "Le centre de gravité du levier"], bonne: 0,
        expl: "Le bras de levier d = OH se mesure <b>perpendiculairement à la droite d'action</b> (en pointillés), pas le long du levier. C'est l'erreur la plus fréquente à l'écrit." },
      { regler: LV(60),
        q: "Pour obtenir le plus grand moment avec la même force, il faut…",
        choix: ["Mettre la force perpendiculaire au levier (θ = 90°)", "La mettre dans l'axe du levier", "La rapprocher de O", "Changer son sens"], bonne: 0,
        expl: "M = F·OA·sin θ est maximal pour sin θ = 1. Appliquer la force <b>loin de O et perpendiculairement</b> : c'est le principe de la clé et de la poignée de porte." },
      { regler: LV(90),
        q: "La flèche courbe autour de O représente…",
        choix: ["Le moment de F en O : son épaisseur suit sa valeur", "La vitesse de rotation du levier", "Le poids du levier", "L'angle θ"], bonne: 0,
        expl: "Elle montre le <b>sens de rotation</b> que F tend à donner au levier autour de O, et son épaisseur grandit avec |M| = F·d, en N·m." },
    ],
  };

  /* ---------------------------------------------------------------- DS 02
     Frottement : lire le cône (animation « Quand est-ce que ça glisse ? »). Le bloc glisse quand tan α > f. */
  const BL = (al, f = 0.5, m = 4) => ({ "inclinaison du plan": al, "coefficient d'adherence": f, "masse du bloc": m });
  SIP.OBSERVE_BAC["meca-frottement"] = {
    titre: "Lire le cône de frottement",
    consigne: "Le bloc est posé sur le plan incliné : regarde s'il tient ou s'il glisse, et où se place l'action R du plan par rapport au cône, puis réponds.",
    questions: [
      { regler: BL(20),
        q: "Plan incliné à 20°, f = 0,5. Le bloc…",
        choix: ["Tient : R reste dans le cône", "Glisse", "Tient tout juste, à la limite", "Remonte le plan"], bonne: 0,
        expl: "Il tient tant que tan α ≤ f : tan 20° = 0,364 ≤ 0,5. L'action R du plan reste <b>dans le cône</b>, avec T = P·sin α &lt; f·N." },
      { regler: BL(30),
        q: "On incline à <b>30°</b> (f = 0,5). Que fait le bloc ?",
        choix: ["Il glisse : il faudrait que R sorte du cône", "Il tient", "Il tient tout juste", "Il bascule"], bonne: 0,
        expl: "tan 30° = 0,577 &gt; 0,5. Pour tenir, il faudrait T = P·sin α, plus que le maximum f·N : R se cale <b>sur le bord du cône</b> et le bloc descend." },
      { regler: BL(20, 0.3),
        q: "Toujours 20°, mais surface plus glissante (<b>f = 0,3</b>). Le bloc…",
        choix: ["Glisse : tan 20° = 0,36 > 0,3", "Tient", "Tient tout juste", "Ne bouge que si on le pousse"], bonne: 0,
        expl: "Le cône se <b>referme</b> quand f baisse (tan φ = f). À 20°, R devrait sortir du cône : le bloc glisse." },
      { regler: BL(20, 0.5, 8),
        q: "Masse <b>doublée</b> (8 kg), 20°, f = 0,5. Le bloc…",
        choix: ["Tient toujours : la masse ne change pas la condition tan α ≤ f", "Glisse maintenant", "Tient tout juste", "S'enfonce dans le plan"], bonne: 0,
        expl: "P·sin α ≤ f·P·cos α : le poids se <b>simplifie</b>. Toutes les flèches doublent, mais leurs directions ne changent pas ; R reste dans le cône." },
      { regler: BL(27),
        q: "α = <b>27°</b>, f = 0,5. Le bloc…",
        choix: ["Glisse, de justesse : tan 27° = 0,51 > 0,5", "Tient largement", "Tient exactement à la limite", "Remonte"], bonne: 0,
        expl: "L'angle limite vaut φ = arctan 0,5 = 26,6°. À 27°, on l'a dépassé d'un rien : le bloc part <b>lentement</b>, l'excès de P·sin α sur f·N est faible." },
      { regler: BL(45, 1),
        q: "α = 45° et <b>f = 1</b>. Le bloc…",
        choix: ["Tient, exactement à la limite : tan 45° = 1 = f", "Glisse", "Tient largement", "Glisse vite"], bonne: 0,
        expl: "tan α = f : R est <b>sur le bord</b> du cône, T = f·N exactement. Un rien de plus et il part : c'est ainsi qu'on mesure f sur un plan incliné." },
      { regler: BL(20),
        q: "La flèche N (bleue) est…",
        choix: ["Perpendiculaire au plan incliné", "Verticale", "Parallèle au plan", "Dirigée vers le bas"], bonne: 0,
        expl: "N est la composante <b>normale</b> de l'action du plan : perpendiculaire à la surface de contact, N = P·cos α." },
      { regler: BL(20),
        q: "La flèche T (verte) est…",
        choix: ["Parallèle au plan, vers le haut : elle retient le bloc", "Perpendiculaire au plan", "Verticale", "Parallèle au plan, vers le bas"], bonne: 0,
        expl: "T est la composante <b>tangentielle</b> : elle s'oppose au glissement que le poids voudrait produire, T = P·sin α tant que le bloc tient." },
      { regler: BL(20),
        q: "Les deux droites grises issues du point de contact délimitent…",
        choix: ["Le cône de frottement, de demi-angle φ avec tan φ = f", "L'angle α", "La trajectoire du bloc", "La direction du poids"], bonne: 0,
        expl: "Tout ce que le plan peut exercer sur le bloc est <b>dans ce cône</b> : |T| ≤ f·N, soit un angle au plus φ avec la normale." },
      { regler: BL(20, 0.8),
        q: "f passe de 0,5 à <b>0,8</b>. Le cône…",
        choix: ["S'ouvre : φ grandit, le bloc tiendra jusqu'à un angle plus grand", "Se referme", "Ne change pas", "Disparaît"], bonne: 0,
        expl: "tan φ = f : φ passe de 26,6° à 38,7°. Plus la surface accroche, plus le cône est <b>ouvert</b>." },
      { regler: BL(20),
        q: "Tant que le bloc tient, l'action R du plan (flèche grise) est…",
        choix: ["Verticale, opposée au poids", "Perpendiculaire au plan", "Parallèle au plan", "Nulle"], bonne: 0,
        expl: "Deux forces seulement, P et R : à l'équilibre, elles sont <b>opposées</b>. R est donc verticale, inclinée de α par rapport à la normale au plan." },
      { regler: BL(35),
        q: "À 35°, le bloc glisse. Alors T vaut…",
        choix: ["f·N : R est sur le bord du cône", "P·sin α", "Zéro", "P"], bonne: 0,
        expl: "En glissement, le frottement est à son <b>maximum</b> T = f·N, inférieur à P·sin α : la différence accélère le bloc vers le bas." },
    ],
  };
})(window.SIP);
